name:                dnd-chat
version:             0.1.0.0
github:              "testare/dnd-chat"
license:             BSD3
author:              "Logan Woodbury"
maintainer:          "testare.i9z@gmail.com"
copyright:           "2018 Logan Woodbury"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/dnd-chat#readme>

dependencies:
- base >= 4.7 && < 5
- network >= 2.6 && < 2.7
- bytestring >= 0.10 && < 0.11
- haskeline >= 0.7 && < 0.8
- ansi-terminal >= 0.8 && < 0.9
- terminal-size >= 0.3 && < 0.4
- async >= 2.1 && < 2.3
- stm >= 2.4.5 && < 2.5
- process >= 1.6 && < 1.7
- containers


library:
  source-dirs: src

executables:
  c:
    main:                Client
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dnd-chat
  s:
    main:                Server
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dnd-chat
  dnd-chat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dnd-chat

tests:
  dnd-chat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dnd-chat
